
id = "AshAxolotl.HideHUD"
name = "HideHUD"
description = "Hide HUD using a config"
version = "1.0.3"
homepage = "https://github.com/AshAxolotl/HideHUD"
author = "AshAxolotl"

icon = "icon.png"
readme = "README.md"

[project]
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"

[[dependencies]]
id = "TackleBox"
thunderstore_version = "PuppyGirl-TackleBox-0.4.1"

[[dependencies]]
id = "BlueberryWolfi.APIs"
thunderstore_version = "BlueberryWolfi-BlueberryWolfiAPIs-1.0.2"
